
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_BASE_URL: 'http://localhost:8080/api/v1'
  };
